INSERT INTO categories (category_id, category_name, alias) VALUES (1, 'Afghan', 'afghani');
INSERT INTO categories (category_id, category_name, alias) VALUES (2, 'African', 'african');
INSERT INTO categories (category_id, category_name, alias) VALUES (3, 'Senegalese', 'senegalese');
INSERT INTO categories (category_id, category_name, alias) VALUES (4, 'South African', 'southafrican');
INSERT INTO categories (category_id, category_name, alias) VALUES (5, 'American (New)', 'newamerican');
INSERT INTO categories (category_id, category_name, alias) VALUES (6, 'American (Traditional)', 'tradamerican');
INSERT INTO categories (category_id, category_name, alias) VALUES (7, 'Arabian', 'arabian');
INSERT INTO categories (category_id, category_name, alias) VALUES (8, 'Argentine', 'argentine');
INSERT INTO categories (category_id, category_name, alias) VALUES (9, 'Armenian', 'armenian');
INSERT INTO categories (category_id, category_name, alias) VALUES (10, 'Asian Fusion', 'asianfusion');
INSERT INTO categories (category_id, category_name, alias) VALUES (11, 'Australian', 'australian');
INSERT INTO categories (category_id, category_name, alias) VALUES (12, 'Austrian', 'austrian');
INSERT INTO categories (category_id, category_name, alias) VALUES (13, 'Bangladeshi', 'bangladeshi');
INSERT INTO categories (category_id, category_name, alias) VALUES (14, 'Barbeque', 'bbq');
INSERT INTO categories (category_id, category_name, alias) VALUES (15, 'Basque', 'basque');
INSERT INTO categories (category_id, category_name, alias) VALUES (16, 'Belgian', 'belgian');
INSERT INTO categories (category_id, category_name, alias) VALUES (17, 'Brasseries', 'brasseries');
INSERT INTO categories (category_id, category_name, alias) VALUES (18, 'Brazilian', 'brazilian');
INSERT INTO categories (category_id, category_name, alias) VALUES (19, 'Breakfast & Brunch', 'breakfast_brunch');
INSERT INTO categories (category_id, category_name, alias) VALUES (20, 'Pancakes', 'pancakes');
INSERT INTO categories (category_id, category_name, alias) VALUES (21, 'British', 'british');
INSERT INTO categories (category_id, category_name, alias) VALUES (22, 'Buffets', 'buffets');
INSERT INTO categories (category_id, category_name, alias) VALUES (23, 'Bulgarian', 'bulgarian');
INSERT INTO categories (category_id, category_name, alias) VALUES (24, 'Burgers', 'burgers');
INSERT INTO categories (category_id, category_name, alias) VALUES (25, 'Burmese', 'burmese');
INSERT INTO categories (category_id, category_name, alias) VALUES (26, 'Cafes', 'cafes');
INSERT INTO categories (category_id, category_name, alias) VALUES (27, 'Themed Cafes', 'themedcafes');
INSERT INTO categories (category_id, category_name, alias) VALUES (28, 'Cafeteria', 'cafeteria');
INSERT INTO categories (category_id, category_name, alias) VALUES (29, 'Cajun/Creole', 'cajun');
INSERT INTO categories (category_id, category_name, alias) VALUES (30, 'Cambodian', 'cambodian');
INSERT INTO categories (category_id, category_name, alias) VALUES (31, 'Caribbean', 'caribbean');
INSERT INTO categories (category_id, category_name, alias) VALUES (32, 'Dominican', 'dominican');
INSERT INTO categories (category_id, category_name, alias) VALUES (33, 'Haitian', 'haitian');
INSERT INTO categories (category_id, category_name, alias) VALUES (34, 'Puerto Rican', 'puertorican');
INSERT INTO categories (category_id, category_name, alias) VALUES (35, 'Trinidadian', 'trinidadian');
INSERT INTO categories (category_id, category_name, alias) VALUES (36, 'Catalan', 'catalan');
INSERT INTO categories (category_id, category_name, alias) VALUES (37, 'Cheesesteaks', 'cheesesteaks');
INSERT INTO categories (category_id, category_name, alias) VALUES (38, 'Chicken Shop', 'chickenshop');
INSERT INTO categories (category_id, category_name, alias) VALUES (39, 'Chicken Wings', 'chicken_wings');
INSERT INTO categories (category_id, category_name, alias) VALUES (40, 'Chinese', 'chinese');
INSERT INTO categories (category_id, category_name, alias) VALUES (41, 'Cantonese', 'cantonese');
INSERT INTO categories (category_id, category_name, alias) VALUES (42, 'Dim Sum', 'dimsum');
INSERT INTO categories (category_id, category_name, alias) VALUES (43, 'Hainan', 'hainan');
INSERT INTO categories (category_id, category_name, alias) VALUES (44, 'Shanghainese', 'shanghainese');
INSERT INTO categories (category_id, category_name, alias) VALUES (45, 'Szechuan', 'szechuan');
INSERT INTO categories (category_id, category_name, alias) VALUES (46, 'Comfort Food', 'comfortfood');
INSERT INTO categories (category_id, category_name, alias) VALUES (47, 'Creperies', 'creperies');
INSERT INTO categories (category_id, category_name, alias) VALUES (48, 'Cuban', 'cuban');
INSERT INTO categories (category_id, category_name, alias) VALUES (49, 'Czech', 'czech');
INSERT INTO categories (category_id, category_name, alias) VALUES (50, 'Delis', 'delis');
INSERT INTO categories (category_id, category_name, alias) VALUES (51, 'Diners', 'diners');
INSERT INTO categories (category_id, category_name, alias) VALUES (52, 'Dinner Theater', 'dinnertheater');
INSERT INTO categories (category_id, category_name, alias) VALUES (53, 'Eritrean', 'eritrean');
INSERT INTO categories (category_id, category_name, alias) VALUES (54, 'Ethiopian', 'ethiopian');
INSERT INTO categories (category_id, category_name, alias) VALUES (55, 'Fast Food', 'hotdogs');
INSERT INTO categories (category_id, category_name, alias) VALUES (56, 'Filipino', 'filipino');
INSERT INTO categories (category_id, category_name, alias) VALUES (57, 'Fish & Chips', 'fishnchips');
INSERT INTO categories (category_id, category_name, alias) VALUES (58, 'Fondue', 'fondue');
INSERT INTO categories (category_id, category_name, alias) VALUES (59, 'Food Court', 'food_court');
INSERT INTO categories (category_id, category_name, alias) VALUES (60, 'Food Stands', 'foodstands');
INSERT INTO categories (category_id, category_name, alias) VALUES (61, 'French', 'french');
INSERT INTO categories (category_id, category_name, alias) VALUES (62, 'Mauritius', 'mauritius');
INSERT INTO categories (category_id, category_name, alias) VALUES (63, 'Reunion', 'reunion');
INSERT INTO categories (category_id, category_name, alias) VALUES (64, 'Game Meat', 'gamemeat');
INSERT INTO categories (category_id, category_name, alias) VALUES (65, 'Gastropubs', 'gastropubs');
INSERT INTO categories (category_id, category_name, alias) VALUES (66, 'Georgian', 'georgian');
INSERT INTO categories (category_id, category_name, alias) VALUES (67, 'German', 'german');
INSERT INTO categories (category_id, category_name, alias) VALUES (68, 'Gluten-Free', 'gluten_free');
INSERT INTO categories (category_id, category_name, alias) VALUES (69, 'Greek', 'greek');
INSERT INTO categories (category_id, category_name, alias) VALUES (70, 'Guamanian', 'guamanian');
INSERT INTO categories (category_id, category_name, alias) VALUES (71, 'Halal', 'halal');
INSERT INTO categories (category_id, category_name, alias) VALUES (72, 'Hawaiian', 'hawaiian');
INSERT INTO categories (category_id, category_name, alias) VALUES (73, 'Himalayan/Nepalese', 'himalayan');
INSERT INTO categories (category_id, category_name, alias) VALUES (74, 'Honduran', 'honduran');
INSERT INTO categories (category_id, category_name, alias) VALUES (75, 'Hong Kong Style Cafe', 'hkcafe');
INSERT INTO categories (category_id, category_name, alias) VALUES (76, 'Hot Dogs', 'hotdog');
INSERT INTO categories (category_id, category_name, alias) VALUES (77, 'Hot Pot', 'hotpot');
INSERT INTO categories (category_id, category_name, alias) VALUES (78, 'Hungarian', 'hungarian');
INSERT INTO categories (category_id, category_name, alias) VALUES (79, 'Iberian', 'iberian');
INSERT INTO categories (category_id, category_name, alias) VALUES (80, 'Indian', 'indpak');
INSERT INTO categories (category_id, category_name, alias) VALUES (81, 'Indonesian', 'indonesian');
INSERT INTO categories (category_id, category_name, alias) VALUES (82, 'Irish', 'irish');
INSERT INTO categories (category_id, category_name, alias) VALUES (83, 'Italian', 'italian');
INSERT INTO categories (category_id, category_name, alias) VALUES (84, 'Calabrian', 'calabrian');
INSERT INTO categories (category_id, category_name, alias) VALUES (85, 'Sardinian', 'sardinian');
INSERT INTO categories (category_id, category_name, alias) VALUES (86, 'Sicilian', 'sicilian');
INSERT INTO categories (category_id, category_name, alias) VALUES (87, 'Tuscan', 'tuscan');
INSERT INTO categories (category_id, category_name, alias) VALUES (88, 'Japanese', 'japanese');
INSERT INTO categories (category_id, category_name, alias) VALUES (89, 'Conveyor Belt Sushi', 'conveyorsushi');
INSERT INTO categories (category_id, category_name, alias) VALUES (90, 'Izakaya', 'izakaya');
INSERT INTO categories (category_id, category_name, alias) VALUES (91, 'Japanese Curry', 'japacurry');
INSERT INTO categories (category_id, category_name, alias) VALUES (92, 'Ramen', 'ramen');
INSERT INTO categories (category_id, category_name, alias) VALUES (93, 'Teppanyaki', 'teppanyaki');
INSERT INTO categories (category_id, category_name, alias) VALUES (94, 'Kebab', 'kebab');
INSERT INTO categories (category_id, category_name, alias) VALUES (95, 'Korean', 'korean');
INSERT INTO categories (category_id, category_name, alias) VALUES (96, 'Kosher', 'kosher');
INSERT INTO categories (category_id, category_name, alias) VALUES (97, 'Laotian', 'laotian');
INSERT INTO categories (category_id, category_name, alias) VALUES (98, 'Latin American', 'latin');
INSERT INTO categories (category_id, category_name, alias) VALUES (99, 'Colombian', 'colombian');
INSERT INTO categories (category_id, category_name, alias) VALUES (100, 'Salvadoran', 'salvadoran');
INSERT INTO categories (category_id, category_name, alias) VALUES (101, 'Venezuelan', 'venezuelan');
INSERT INTO categories (category_id, category_name, alias) VALUES (102, 'Live/Raw Food', 'raw_food');
INSERT INTO categories (category_id, category_name, alias) VALUES (103, 'Malaysian', 'malaysian');
INSERT INTO categories (category_id, category_name, alias) VALUES (104, 'Mediterranean', 'mediterranean');
INSERT INTO categories (category_id, category_name, alias) VALUES (105, 'Falafel', 'falafel');
INSERT INTO categories (category_id, category_name, alias) VALUES (106, 'Mexican', 'mexican');
INSERT INTO categories (category_id, category_name, alias) VALUES (107, 'Tacos', 'tacos');
INSERT INTO categories (category_id, category_name, alias) VALUES (108, 'Middle Eastern', 'mideastern');
INSERT INTO categories (category_id, category_name, alias) VALUES (109, 'Egyptian', 'egyptian');
INSERT INTO categories (category_id, category_name, alias) VALUES (110, 'Lebanese', 'lebanese');
INSERT INTO categories (category_id, category_name, alias) VALUES (111, 'Modern European', 'modern_european');
INSERT INTO categories (category_id, category_name, alias) VALUES (112, 'Mongolian', 'mongolian');
INSERT INTO categories (category_id, category_name, alias) VALUES (113, 'Moroccan', 'moroccan');
INSERT INTO categories (category_id, category_name, alias) VALUES (114, 'New Mexican Cuisine', 'newmexican');
INSERT INTO categories (category_id, category_name, alias) VALUES (115, 'Nicaraguan', 'nicaraguan');
INSERT INTO categories (category_id, category_name, alias) VALUES (116, 'Noodles', 'noodles');
INSERT INTO categories (category_id, category_name, alias) VALUES (117, 'Pakistani', 'pakistani');
INSERT INTO categories (category_id, category_name, alias) VALUES (118, 'Pan Asian', 'panasian');
INSERT INTO categories (category_id, category_name, alias) VALUES (119, 'Persian/Iranian', 'persian');
INSERT INTO categories (category_id, category_name, alias) VALUES (120, 'Peruvian', 'peruvian');
INSERT INTO categories (category_id, category_name, alias) VALUES (121, 'Pizza', 'pizza');
INSERT INTO categories (category_id, category_name, alias) VALUES (122, 'Polish', 'polish');
INSERT INTO categories (category_id, category_name, alias) VALUES (123, 'Polynesian', 'polynesian');
INSERT INTO categories (category_id, category_name, alias) VALUES (124, 'Pop-Up Restaurants', 'popuprestaurants');
INSERT INTO categories (category_id, category_name, alias) VALUES (125, 'Portuguese', 'portuguese');
INSERT INTO categories (category_id, category_name, alias) VALUES (126, 'Poutineries', 'poutineries');
INSERT INTO categories (category_id, category_name, alias) VALUES (127, 'Russian', 'russian');
INSERT INTO categories (category_id, category_name, alias) VALUES (128, 'Salad', 'salad');
INSERT INTO categories (category_id, category_name, alias) VALUES (129, 'Sandwiches', 'sandwiches');
INSERT INTO categories (category_id, category_name, alias) VALUES (130, 'Scandinavian', 'scandinavian');
INSERT INTO categories (category_id, category_name, alias) VALUES (131, 'Scottish', 'scottish');
INSERT INTO categories (category_id, category_name, alias) VALUES (132, 'Seafood', 'seafood');
INSERT INTO categories (category_id, category_name, alias) VALUES (133, 'Singaporean', 'singaporean');
INSERT INTO categories (category_id, category_name, alias) VALUES (134, 'Slovakian', 'slovakian');
INSERT INTO categories (category_id, category_name, alias) VALUES (135, 'Somali', 'somali');
INSERT INTO categories (category_id, category_name, alias) VALUES (136, 'Soul Food', 'soulfood');
INSERT INTO categories (category_id, category_name, alias) VALUES (137, 'Soup', 'soup');
INSERT INTO categories (category_id, category_name, alias) VALUES (138, 'Southern', 'southern');
INSERT INTO categories (category_id, category_name, alias) VALUES (139, 'Spanish', 'spanish');
INSERT INTO categories (category_id, category_name, alias) VALUES (140, 'Sri Lankan', 'srilankan');
INSERT INTO categories (category_id, category_name, alias) VALUES (141, 'Steakhouses', 'steak');
INSERT INTO categories (category_id, category_name, alias) VALUES (142, 'Supper Clubs', 'supperclubs');
INSERT INTO categories (category_id, category_name, alias) VALUES (143, 'Sushi Bars', 'sushi');
INSERT INTO categories (category_id, category_name, alias) VALUES (144, 'Syrian', 'syrian');
INSERT INTO categories (category_id, category_name, alias) VALUES (145, 'Taiwanese', 'taiwanese');
INSERT INTO categories (category_id, category_name, alias) VALUES (146, 'Tapas Bars', 'tapas');
INSERT INTO categories (category_id, category_name, alias) VALUES (147, 'Tapas/Small Plates', 'tapasmallplates');
INSERT INTO categories (category_id, category_name, alias) VALUES (148, 'Tex-Mex', 'tex-mex');
INSERT INTO categories (category_id, category_name, alias) VALUES (149, 'Thai', 'thai');
INSERT INTO categories (category_id, category_name, alias) VALUES (150, 'Turkish', 'turkish');
INSERT INTO categories (category_id, category_name, alias) VALUES (151, 'Ukrainian', 'ukrainian');
INSERT INTO categories (category_id, category_name, alias) VALUES (152, 'Uzbek', 'uzbek');
INSERT INTO categories (category_id, category_name, alias) VALUES (153, 'Vegan', 'vegan');
INSERT INTO categories (category_id, category_name, alias) VALUES (154, 'Vegetarian', 'vegetarian');
INSERT INTO categories (category_id, category_name, alias) VALUES (155, 'Vietnamese', 'vietnamese');
INSERT INTO categories (category_id, category_name, alias) VALUES (156, 'Waffles', 'waffles');
INSERT INTO categories (category_id, category_name, alias) VALUES (157, 'Wraps', 'wraps');
