FROM python:3.7-alpine
WORKDIR /usr/src/app
ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_ENV development
ENV PYTHONUNBUFFERED=0
ENV YELP_KEY=m6L_OCZi244hShQ4cEOK_c1nPYl9dusC43RVQRYgBlZVfNwNk3kiWBp5qDbtOdeHGUdW09VSnnTRQLSGUBpdtr2a5gT2-Xr2QBWopE-HKUkczE1-AZpMGN5KovSgXHYx
ENV GOOGLE_KEY=AIzaSyA6nz-5DyNQqIM-TBMrSf9Vy65w3R8pEhE
# RUN apk add --no-cache gcc musl-dev linux-headers
RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
CMD ["flask", "run"]